name: gh-pages
on:
  push:
    branches: master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - run: bundle install
      - run: bundle exec jekyll build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: Deploy
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
