name: gh-pages
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - run: bundle exec jekyll build
      - id: cname
        run: |
          if [ ${{ github.event.repository.fork }} = 'false' ]; then
            echo "cname=www.electrode.io" >> "$GITHUB_OUTPUT"
          fi
      - uses: peaceiris/actions-gh-pages@v3
        with:
          cname: ${{ steps.cname.outputs.cname }}
          commit_message: Deploy
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
